version: '3'
services:

  elliotts_zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: elliotts_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  broker1:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker1
    ports:
        - '9091:9091'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker1:9092,EXTERNAL://localhost:9091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=elliotts_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    
    depends_on:
      - elliotts_zookeeper

  broker2:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker2
    ports:
        - '9094:9094'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker2:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=elliotts_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    
    depends_on:
      - elliotts_zookeeper

  broker3:
    image: 'bitnami/kafka:latest'
    container_name: kafka_broker3
    ports:
        - '9093:9093'
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_broker3:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=elliotts_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

    depends_on:
      - elliotts_zookeeper

    

  